name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '25'
          distribution: 'oracle'

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build the proxy jar
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}-${{ steps.date.outputs.date }}"
          release_name: "${{ github.run_id }} - ${{ steps.date.outputs.date }}"
          files: build/libs/your-jar-file.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
